### ISSUE TITLE
[BUG] CORDEX build failing in v1.0.0b2

### ISSUE THREAD

**Issue by marc-white** [ACCESS-NRI/access-nri-intake-catalog#283]
# Describe the bug

The `ig45` Cordex data is failing to build in `v1.0.0b2` due to a metadata issue:

```
Traceback (most recent call last):
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.11/lib/python3.11/site-packages/access_nri_intake/cli.py", line 65, in _parse_build_inputs
    metadata = load_metadata_yaml(
               ^^^^^^^^^^^^^^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.11/lib/python3.11/site-packages/access_nri_intake/utils.py", line 79, in load_metadata_yaml
    validate_against_schema(metadata, jsonschema)
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.11/lib/python3.11/site-packages/access_nri_intake/utils.py", line 118, in validate_against_schema
    raise jsonschema.ValidationError(issue_str)
jsonschema.exceptions.ValidationError:
01 | frequency : 'day' is not valid under any of the given schemas
02 | frequency : 'mon' is not valid under any of the given schemas
03 | related_experiments : None is not of type 'array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.11/bin/catalog-build", line 10, in <module>
    sys.exit(build())
             ^^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.11/lib/python3.11/site-packages/access_nri_intake/cli.py", line 212, in build
    parsed_sources = _parse_build_inputs(config_yamls, build_path, data_base_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.11/lib/python3.11/site-packages/access_nri_intake/cli.py", line 69, in _parse_build_inputs
    raise MetadataCheckError(
access_nri_intake.cli.MetadataCheckError: Failed to validate metadata.yaml @ /g/data/xp65/admin/intake/metadata/cordex_ig45. See traceback for details.
```

# To Reproduce

Attempt to build the catalog using `conda/analysis3-24.11`.

# Additional context

Investigating.

**Comment by marc-white** [comment]
I think there's just some minor metadata errors in `/g/data/xp65/admin/intake/metadata/cordex_ig45/metadata.yaml`. I can update that on `xp65` and restart the build, and then fix the issue in the reference repo copy.
